name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    permissions:
      id-token: write  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tool
        run: pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
